from CiscoFunctions import *
setup("/Users/ezraodio/Documents/sample.xlsx", "Summary")
deleteCol("Host ID/Mac ID")
deleteCol("Service Type")
deleteCol("Takeover Line")
deleteCol("Quantity UOM")
deleteCol("Price UOM")
deleteCol("Extended Net Price")
deleteCol("End Customer ID")
deleteCol("End Customer Address Line 2")
deleteCol("Product PO")
deleteCol("Product SO")
deleteCol("Initial Term (Months)")
deleteCol("Billing Frequency")
deleteCol("Automatically Renews For")
deleteCol("Subscription ID")
calcEUCost()
highlight()
warnClient()
calcDiscount()
resizeColumns()
makePretty()
deleteRows()
addFilters()
hideRows()
name()
